import type { Product } from "../types";

/**
 * Mock product catalogue. In production this data comes from
 * POST /api/products/search filtered by location, item type, and budget.
 * Images are placeholder photos (picsum) — swap for a real CDN later.
 */
export const PRODUCTS: Product[] = [
  {
    id: "p-sofa-01",
    name: "Halden 3-Seater Sofa",
    category: "furniture",
    price: 1890,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-sofa/600/400",
    description: "Deep-seated boucle sofa with solid oak legs.",
  },
  {
    id: "p-coffee-01",
    name: "Marlow Travertine Coffee Table",
    category: "furniture",
    price: 640,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-coffee/600/400",
    description: "Sculptural travertine table with a honed finish.",
  },
  {
    id: "p-bed-01",
    name: "Nordic Upholstered King Bed",
    category: "furniture",
    price: 1450,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-bed/600/400",
    description: "Low-profile bed frame with a linen headboard.",
  },
  {
    id: "p-dining-01",
    name: "Aria Extendable Dining Table",
    category: "furniture",
    price: 1120,
    currency: "USD",
    quantity: 1,
    locationAvailability: false,
    image: "https://picsum.photos/seed/prod-dining/600/400",
    description: "Solid ash dining table seating up to eight.",
  },
  {
    id: "p-chair-01",
    name: "Lyle Accent Chair",
    category: "furniture",
    price: 420,
    currency: "USD",
    quantity: 2,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-chair/600/400",
    description: "Curved lounge chair in warm caramel leather.",
  },
  {
    id: "p-rug-01",
    name: "Dune Hand-Knotted Rug",
    category: "decor",
    price: 560,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-rug/600/400",
    description: "Wool-blend rug in a soft sand tonal weave.",
  },
  {
    id: "p-art-01",
    name: "Horizon Framed Art Set",
    category: "decor",
    price: 280,
    currency: "USD",
    quantity: 3,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-art/600/400",
    description: "Set of three abstract prints in oak frames.",
  },
  {
    id: "p-plant-01",
    name: "Sculptural Indoor Planter",
    category: "decor",
    price: 150,
    currency: "USD",
    quantity: 2,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-plant/600/400",
    description: "Ribbed ceramic planter with a live fiddle-leaf fig.",
  },
  {
    id: "p-curtain-01",
    name: "Sheer Linen Drapery",
    category: "decor",
    price: 320,
    currency: "USD",
    quantity: 2,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-curtain/600/400",
    description: "Floor-length linen curtains that diffuse daylight.",
  },
  {
    id: "p-ceil-01",
    name: "Orbit Pendant Light",
    category: "lighting",
    price: 390,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-ceil/600/400",
    description: "Brushed brass pendant with opal glass diffuser.",
  },
  {
    id: "p-floor-01",
    name: "Arc Floor Lamp",
    category: "lighting",
    price: 240,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-floor/600/400",
    description: "Adjustable arc lamp with a marble base.",
  },
  {
    id: "p-table-lamp-01",
    name: "Pebble Table Lamp",
    category: "lighting",
    price: 130,
    currency: "USD",
    quantity: 2,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-tlamp/600/400",
    description: "Hand-glazed ceramic lamp with a linen shade.",
  },
  {
    id: "p-outseat-01",
    name: "Terra Outdoor Lounge Set",
    category: "exterior",
    price: 1680,
    currency: "USD",
    quantity: 1,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-outseat/600/400",
    description: "Weather-resistant modular seating in teak and rope.",
  },
  {
    id: "p-patio-01",
    name: "Slate Patio Dining Table",
    category: "exterior",
    price: 890,
    currency: "USD",
    quantity: 1,
    locationAvailability: false,
    image: "https://picsum.photos/seed/prod-patio/600/400",
    description: "Powder-coated aluminium table for six.",
  },
  {
    id: "p-path-01",
    name: "Lumen Pathway Lights",
    category: "exterior",
    price: 210,
    currency: "USD",
    quantity: 6,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-path/600/400",
    description: "Solar bollard lights with a warm glow.",
  },
  {
    id: "p-garden-01",
    name: "Terracotta Garden Planters",
    category: "exterior",
    price: 260,
    currency: "USD",
    quantity: 4,
    locationAvailability: true,
    image: "https://picsum.photos/seed/prod-garden/600/400",
    description: "Set of frost-proof terracotta planters.",
  },
];

export function getProductById(id: string) {
  return PRODUCTS.find((p) => p.id === id);
}
