"""add image_generation_status to design_requests

Revision ID: 202607240002
Revises: 202607240001
Create Date: 2026-07-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202607240002'
down_revision: Union[str, None] = '202607240001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_requests', sa.Column('image_generation_status', sa.String(length=32), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_requests', 'image_generation_status')
    # ### end Alembic commands ###
